export interface FAQItem {
  question: string;
  answer: string;
  category?: "general" | "technical" | "installation" | "pricing" | string;
}

export const faqsData: FAQItem[] = [
  {
    question: "What is a Wind Driven Turbo Roof Ventilator and how does it operate without electricity?",
    answer: "A Wind Driven Turbo Ventilator is an aerodynamic natural exhaust system installed on factory and warehouse rooftops. It operates on two natural physical principles: centrifugal force generated by external wind passing over the curved aerodynamic blades, and the thermal siphon (chimney / stack effect) created by warm, buoyant indoor air rising towards the roof. As the blades spin, they create a continuous low-pressure zone that vigorously extracts trapped hot air, smoke, humidity, and noxious fumes from the shed without consuming any electrical energy.",
    category: "general"
  },
  {
    question: "What are the primary materials (MOC) used in Shreeji Simpovent Turbo Ventilators?",
    answer: "Shreeji Simpovent ventilators are manufactured using premium Hindalco Make Aluminium (Grade 8011/3003) for the aerodynamic blades and rotor cage, combined with heavy-gauge Stainless Steel (Grade SS 304) for top covers, bottom rings, and fasteners. For corrosive chemical environments, 100% SS 304 or SS 316 constructions are also custom-engineered.",
    category: "technical"
  },
  {
    question: "What bearings are used in the ventilator, and do they require regular greasing?",
    answer: "Our wind ventilators utilize dual precision HCH 6001 ZZ / 6001-2RS deep-groove sealed ball bearings pre-lubricated with high-temperature synthetic grease. They are completely sealed against moisture, airborne dust, and acidic fumes, making our ventilators 100% maintenance-free for over a decade.",
    category: "technical"
  },
  {
    question: "How many wind turbine ventilators are required for my industrial shed or warehouse?",
    answer: "The number of ventilators required depends on three variables: shed volume (Length x Width x Average Height in feet), the industry type (which dictates required Air Changes Per Hour or ACPH, typically 10 to 30 ACPH), and average local wind speed. Our interactive online Ventilation Calculator accurately determines the required CFM and total number of 21-inch or 24-inch ventilators required for your facility.",
    category: "installation"
  },
  {
    question: "Can Shreeji Turbo Ventilators withstand heavy rainstorms, cyclonic winds, and water leakage?",
    answer: "Yes, 100%. The aerodynamic curved blade contour is engineered with dual-channel capillary water dams that prevent raindrop ingress even during driving horizontal monsoon rains. Additionally, our matching custom-molded FRP (Fiberglass Reinforced Plastic) or Polycarbonate base plates perfectly overlap your existing metal/asbestos roof profiles, sealing the opening completely against leaks.",
    category: "technical"
  },
  {
    question: "What is the difference between a natural wind ventilator and a motorized roof ventilator?",
    answer: "A natural wind ventilator operates 100% free of electricity using ambient wind and thermal convection, ideal for general heat and humidity exhaustion. A motorized roof ventilator or motorized turbo ventilator incorporates an auxiliary explosion-proof electric motor (or dual-drive hybrid mechanism) that can be switched on during peak heat generation, heavy welding/casting smoke surges, or stagnant wind conditions to force high-velocity air exhaust.",
    category: "technical"
  },
  {
    question: "What roof types and profiles are compatible with your base plates?",
    answer: "Our base plates are custom matched and profiled for all industrial roof types, including Trapezoidal metal sheets (Tata Bluescope, Kirby, JSW, Jindal, Everest), Corrugated Asbestos Cement (AC) sheets, Pre-Engineered Building (PEB) roofs, Standing Seam roofs, and RCC concrete roof curbs.",
    category: "installation"
  },
  {
    question: "What warranty and service support does Shreeji Sales Corporation provide across India?",
    answer: "All Shreeji Simpovent Turbo Ventilators carry a comprehensive 10-Year structural and manufacturing warranty. We maintain a pan-India distribution network with ready-stock inventory for immediate dispatch to Maharashtra, Gujarat, Rajasthan, Karnataka, Tamil Nadu, Delhi NCR, and nationwide.",
    category: "general"
  }
];
